FROM python:3.11-slim

RUN apt-get update && apt-get install -y gcc libpq-dev

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

ENV PYTHONUNBUFFERED=1

# Запуск Celery
CMD ["celery", "-A", "app.utils.celary.redis_config.celery_app", "worker", "--loglevel=info"]
