version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:21.1.2
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
    command: ["start-dev"]
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
  redis:
    image: redis
    container_name: KernAI-redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  keycloak_data:
  postgres_data:
  redis_data:


networks:
  keycloak-network:
